name: build-and-push-tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set image tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      - name: Build image ${{ github.repository_owner }}/loginsrv:${{ steps.vars.outputs.tag }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/loginsrv:${{ steps.vars.outputs.tag }}